ARCHS = arm64 arm64e

include $(THEOS_MAKE_PATH)/common.mk

TWEAK_NAME = MitsuhaForeverSoundCloud
$(TWEAK_NAME)_FILES = SCTweak.xm
$(TWEAK_NAME)_LIBRARIES += mitsuhaforever
$(TWEAK_NAME)_FRAMEWORKS += UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/tweak.mk